defmodule Flatbuf.ConformanceTest do
  @moduledoc """
  Upstream-corpus conformance.

  We don't make up our own test schemas: this module enumerates every
  `.fbs` file under `google/flatbuffers/tests/` (pinned via
  `mix flatbuf.fetch_fixtures`) and runs our parser+resolver against
  each. The expected outcome — `:ok` or a specific normalized error —
  lives in `test/fixtures/conformance_manifest.exs`. The manifest is
  generated by `mix flatbuf.conformance.update`.

  A green run means: every schema produced the *same* outcome it
  produced when the manifest was last refreshed. A red run means a
  behaviour change — either we just implemented something (good — run
  the update task and commit), or we just regressed (bad — go look).

  Errors like `{:unsupported_in_phase1, :union}` are perfectly fine
  manifest entries; they represent the bits we haven't built yet.
  """

  use ExUnit.Case, async: true

  alias Flatbuf.Test.Upstream

  @manifest Upstream.load_manifest()
  @files if Upstream.available?(), do: Upstream.all_fbs(), else: []

  if @files == [] do
    @tag :skip
    test "upstream corpus is present" do
      flunk("Run `mix flatbuf.fetch_fixtures` to pull the corpus.")
    end
  else
    test "manifest covers every upstream .fbs" do
      missing = Enum.filter(@files, &(!Map.has_key?(@manifest, &1)))

      if missing != [] do
        flunk("""
        These upstream schemas have no manifest entry:

          #{Enum.join(missing, "\n  ")}

        Run `mix flatbuf.conformance.update` to record their current outcome.
        """)
      end
    end

    for relative <- @files do
      @relative relative
      @expected Map.get(@manifest, relative)

      test "schema #{relative}" do
        actual = Upstream.run_schema(@relative)

        if actual != @expected do
          flunk("""
          Behaviour changed for #{@relative}.

            expected: #{inspect(@expected)}
            actual:   #{inspect(actual)}

          If the change is intentional (you just implemented a feature),
          run `mix flatbuf.conformance.update` and commit the manifest.
          """)
        end
      end
    end
  end
end
