defmodule Flatbuf.MonsterDifferentialTest do
  @moduledoc """
  Differential test against the upstream reference binary.

  Reads `monsterdata_test.mon` (encoded by flatc) and decodes it with
  our generated code, then compares the resulting JSON shape against
  upstream's `monsterdata_test.json`.

  This is the strongest single signal we have for wire-format
  correctness without needing flatc installed locally — the bytes were
  generated by flatc, the expected decoding was generated by flatc,
  and we sit in the middle.

  Skips with a clear notice if the corpus isn't present.
  """

  use ExUnit.Case, async: false

  alias Flatbuf.Test.Upstream

  @corpus_ok Flatbuf.Test.Upstream.available?()

  if @corpus_ok do
    @tests_root Upstream.tests_root()
    @schema Path.join(@tests_root, "monster_test.fbs")
    @binary_path Path.join(@tests_root, "monsterdata_test.mon")

    # Compile the upstream Monster schema at test-file compile time so
    # references like `MyGame.Example.Monster.decode/1` resolve.
    Flatbuf.Test.CodegenCompiler.compile_path!(@schema,
      include_paths: Upstream.include_paths(),
      wire_module: Flatbuf.MonsterDifferentialTest.Wire
    )

    test "verify(monsterdata_test.mon) accepts the upstream buffer" do
      bin = File.read!(@binary_path)
      assert :ok = MyGame.Example.Monster.verify(bin)
    end

    test "verify rejects a truncated upstream buffer" do
      bin = File.read!(@binary_path)
      truncated = binary_part(bin, 0, div(byte_size(bin), 2))
      assert {:error, _} = MyGame.Example.Monster.verify(truncated)
    end

    test "decode(monsterdata_test.mon) recovers the expected Monster" do
      bin = File.read!(@binary_path)
      {:ok, decoded} = MyGame.Example.Monster.decode(bin)

      # Spot-check the well-known fields from monsterdata_test.json.
      assert decoded.name == "MyMonster"
      assert decoded.hp == 80
      assert decoded.mana == 150
      # Color is a (bit_flags) enum upstream — decoded values are lists.
      assert decoded.color == [:Blue]

      assert decoded.pos.x == 1.0
      assert decoded.pos.y == 2.0
      assert decoded.pos.z == 3.0

      assert is_list(decoded.inventory)
      assert length(decoded.inventory) == 5

      assert is_list(decoded.test4)
      assert length(decoded.test4) == 2
    end

    test "decoded fields match the upstream JSON reference" do
      bin = File.read!(@binary_path)
      {:ok, decoded} = MyGame.Example.Monster.decode(bin)

      # Spot-check against the values listed in monsterdata_test.json.
      # We compare via the decoded struct rather than via to_json/JSON
      # round-trip: the upstream .json is flatc's lax-JSON dialect
      # (unquoted keys), which our strict JSON.decode can't parse, and
      # the schema's manual union split (test_type / test with explicit
      # ids) is a known limitation in our codegen.

      assert decoded.name == "MyMonster"
      assert decoded.hp == 80
      assert decoded.mana == 150
      # Color is a (bit_flags) enum upstream — decoded values are lists.
      assert decoded.color == [:Blue]
      assert decoded.inventory == [0, 1, 2, 3, 4]
      assert decoded.vector_of_longs == [1, 100, 10_000, 1_000_000, 100_000_000]
      assert decoded.testarrayofstring == ["test1", "test2"]
      assert decoded.testbool == true
      assert decoded.testarrayofbools == [true, false, true]

      # Vec3 inline struct.
      assert decoded.pos.x == 1.0
      assert decoded.pos.y == 2.0
      assert decoded.pos.z == 3.0
      assert decoded.pos.test1 == 3.0
      # Color is (bit_flags) — pos.test2 decodes to a flag list.
      assert decoded.pos.test2 == [:Green]

      # decoded.pos.test3 is an inline Test struct.
      assert decoded.pos.test3.a == 5
      assert decoded.pos.test3.b == 6

      # Vector of struct (Test).
      [first, second] = decoded.test4
      assert {first.a, first.b} == {10, 20}
      assert {second.a, second.b} == {30, 40}

      # Vector of table (Test… no wait, test5 is actually a vector of structs).
      [t5a, t5b] = decoded.test5
      assert {t5a.a, t5a.b} == {10, 20}
      assert {t5b.a, t5b.b} == {30, 40}

      # Union field — manual-split via explicit (id:8). Variant should be
      # the nested Monster named "Fred".
      assert {:Monster, inner} = decoded.test
      assert inner.name == "Fred"

      # Sub-table.
      assert decoded.enemy.name == "Fred"

      # Test float defaults (NaN/Inf round-trip).
      assert decoded.nan_default == :nan
      assert decoded.inf_default == :infinity
      assert decoded.negative_inf_default == :neg_infinity
    end
  else
    @tag skip: "upstream corpus missing — run `mix flatbuf.fetch_fixtures`"
    test "corpus prerequisites" do
      :ok
    end
  end
end
